/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ControlHubRouteImport } from './routes/control-hub'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HotelBackOfficeAutomationRouteImport } from './routes/hotel-back-office-automation'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrbPreviewRouteImport } from './routes/orb-preview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesBoutiqueGroupRouteImport } from './routes/case-studies.boutique-group'
import { Route as CaseStudiesExtendedStayPortfolioRouteImport } from './routes/case-studies.extended-stay-portfolio'
import { Route as CaseStudiesHiltonManagementCompanyRouteImport } from './routes/case-studies.hilton-management-company'
import { Route as CaseStudiesMidwestPortfolioRouteImport } from './routes/case-studies.midwest-portfolio'
import { Route as CaseStudiesUrbanFullServiceRouteImport } from './routes/case-studies.urban-full-service'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareInnrlyVsActablRouteImport } from './routes/compare.innrly-vs-actabl'
import { Route as CompareInnrlyVsAptechRouteImport } from './routes/compare.innrly-vs-aptech'
import { Route as CompareInnrlyVsHotelEffectivenessRouteImport } from './routes/compare.innrly-vs-hotel-effectiveness'
import { Route as CompareInnrlyVsM3RouteImport } from './routes/compare.innrly-vs-m3'
import { Route as CompareInnrlyVsNimbleRouteImport } from './routes/compare.innrly-vs-nimble'
import { Route as CompareInnrlyVsOtelierRouteImport } from './routes/compare.innrly-vs-otelier'
import { Route as CompareInnrlyVsProfitsageRouteImport } from './routes/compare.innrly-vs-profitsage'
import { Route as ControlHubIndexRouteImport } from './routes/control-hub.index'
import { Route as ControlHubBlogsRouteImport } from './routes/control-hub.blogs'
import { Route as ControlHubLogsRouteImport } from './routes/control-hub.logs'
import { Route as ControlHubNewslettersRouteImport } from './routes/control-hub.newsletters'
import { Route as ControlHubOnboardingRouteImport } from './routes/control-hub.onboarding'
import { Route as ControlHubSeoRouteImport } from './routes/control-hub.seo'
import { Route as ControlHubSettingsRouteImport } from './routes/control-hub.settings'
import { Route as ControlHubTestimonialsRouteImport } from './routes/control-hub.testimonials'
import { Route as ControlHubTrialsRouteImport } from './routes/control-hub.trials'
import { Route as ControlHubUsersRouteImport } from './routes/control-hub.users'
import { Route as IndustriesExtendedStayRouteImport } from './routes/industries.extended-stay'
import { Route as IndustriesFullServiceRouteImport } from './routes/industries.full-service'
import { Route as IndustriesSelectServiceRouteImport } from './routes/industries.select-service'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as IntegrationsCloudbedsRouteImport } from './routes/integrations.cloudbeds'
import { Route as IntegrationsInnFlowRouteImport } from './routes/integrations.inn-flow'
import { Route as IntegrationsM3RouteImport } from './routes/integrations.m3'
import { Route as IntegrationsMewsRouteImport } from './routes/integrations.mews'
import { Route as IntegrationsOperaRouteImport } from './routes/integrations.opera'
import { Route as IntegrationsQuickbooksRouteImport } from './routes/integrations.quickbooks'
import { Route as IntegrationsSageIntacctRouteImport } from './routes/integrations.sage-intacct'
import { Route as LegalAccessibilityRouteImport } from './routes/legal.accessibility'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalSecurityRouteImport } from './routes/legal.security'
import { Route as LegalSubscriptionRouteImport } from './routes/legal.subscription'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ServicesAccountabilityPackRouteImport } from './routes/services.accountability-pack'
import { Route as SolutionsBusinessIntelligenceRouteImport } from './routes/solutions.business-intelligence'
import { Route as SolutionsDocumentVaultRouteImport } from './routes/solutions.document-vault'
import { Route as SolutionsExpenseEntriesRouteImport } from './routes/solutions.expense-entries'
import { Route as SolutionsFinancialControlRouteImport } from './routes/solutions.financial-control'
import { Route as SolutionsInnrlyPayRouteImport } from './routes/solutions.innrly-pay'
import { Route as SolutionsInnrlyShiftRouteImport } from './routes/solutions.innrly-shift'
import { Route as SolutionsLaborWorkforceRouteImport } from './routes/solutions.labor-workforce'
import { Route as SolutionsOperationsAutomationRouteImport } from './routes/solutions.operations-automation'
import { Route as SolutionsReconciliationRouteImport } from './routes/solutions.reconciliation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlHubRoute = ControlHubRouteImport.update({
  id: '/control-hub',
  path: '/control-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBackOfficeAutomationRoute =
  HotelBackOfficeAutomationRouteImport.update({
    id: '/hotel-back-office-automation',
    path: '/hotel-back-office-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbPreviewRoute = OrbPreviewRouteImport.update({
  id: '/orb-preview',
  path: '/orb-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesBoutiqueGroupRoute =
  CaseStudiesBoutiqueGroupRouteImport.update({
    id: '/case-studies/boutique-group',
    path: '/case-studies/boutique-group',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesExtendedStayPortfolioRoute =
  CaseStudiesExtendedStayPortfolioRouteImport.update({
    id: '/case-studies/extended-stay-portfolio',
    path: '/case-studies/extended-stay-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesHiltonManagementCompanyRoute =
  CaseStudiesHiltonManagementCompanyRouteImport.update({
    id: '/case-studies/hilton-management-company',
    path: '/case-studies/hilton-management-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesMidwestPortfolioRoute =
  CaseStudiesMidwestPortfolioRouteImport.update({
    id: '/case-studies/midwest-portfolio',
    path: '/case-studies/midwest-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesUrbanFullServiceRoute =
  CaseStudiesUrbanFullServiceRouteImport.update({
    id: '/case-studies/urban-full-service',
    path: '/case-studies/urban-full-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareInnrlyVsActablRoute = CompareInnrlyVsActablRouteImport.update({
  id: '/compare/innrly-vs-actabl',
  path: '/compare/innrly-vs-actabl',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareInnrlyVsAptechRoute = CompareInnrlyVsAptechRouteImport.update({
  id: '/compare/innrly-vs-aptech',
  path: '/compare/innrly-vs-aptech',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareInnrlyVsHotelEffectivenessRoute =
  CompareInnrlyVsHotelEffectivenessRouteImport.update({
    id: '/compare/innrly-vs-hotel-effectiveness',
    path: '/compare/innrly-vs-hotel-effectiveness',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareInnrlyVsM3Route = CompareInnrlyVsM3RouteImport.update({
  id: '/compare/innrly-vs-m3',
  path: '/compare/innrly-vs-m3',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareInnrlyVsNimbleRoute = CompareInnrlyVsNimbleRouteImport.update({
  id: '/compare/innrly-vs-nimble',
  path: '/compare/innrly-vs-nimble',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareInnrlyVsOtelierRoute = CompareInnrlyVsOtelierRouteImport.update({
  id: '/compare/innrly-vs-otelier',
  path: '/compare/innrly-vs-otelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareInnrlyVsProfitsageRoute =
  CompareInnrlyVsProfitsageRouteImport.update({
    id: '/compare/innrly-vs-profitsage',
    path: '/compare/innrly-vs-profitsage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ControlHubIndexRoute = ControlHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubBlogsRoute = ControlHubBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubLogsRoute = ControlHubLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubNewslettersRoute = ControlHubNewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubOnboardingRoute = ControlHubOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubSeoRoute = ControlHubSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubSettingsRoute = ControlHubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubTestimonialsRoute = ControlHubTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubTrialsRoute = ControlHubTrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => ControlHubRoute,
} as any)
const ControlHubUsersRoute = ControlHubUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ControlHubRoute,
} as any)
const IndustriesExtendedStayRoute = IndustriesExtendedStayRouteImport.update({
  id: '/industries/extended-stay',
  path: '/industries/extended-stay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesFullServiceRoute = IndustriesFullServiceRouteImport.update({
  id: '/industries/full-service',
  path: '/industries/full-service',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSelectServiceRoute = IndustriesSelectServiceRouteImport.update({
  id: '/industries/select-service',
  path: '/industries/select-service',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCloudbedsRoute = IntegrationsCloudbedsRouteImport.update({
  id: '/integrations/cloudbeds',
  path: '/integrations/cloudbeds',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsInnFlowRoute = IntegrationsInnFlowRouteImport.update({
  id: '/integrations/inn-flow',
  path: '/integrations/inn-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsM3Route = IntegrationsM3RouteImport.update({
  id: '/integrations/m3',
  path: '/integrations/m3',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsMewsRoute = IntegrationsMewsRouteImport.update({
  id: '/integrations/mews',
  path: '/integrations/mews',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsOperaRoute = IntegrationsOperaRouteImport.update({
  id: '/integrations/opera',
  path: '/integrations/opera',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsQuickbooksRoute = IntegrationsQuickbooksRouteImport.update({
  id: '/integrations/quickbooks',
  path: '/integrations/quickbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSageIntacctRoute = IntegrationsSageIntacctRouteImport.update({
  id: '/integrations/sage-intacct',
  path: '/integrations/sage-intacct',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/legal/accessibility',
  path: '/legal/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/legal/security',
  path: '/legal/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSubscriptionRoute = LegalSubscriptionRouteImport.update({
  id: '/legal/subscription',
  path: '/legal/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAccountabilityPackRoute =
  ServicesAccountabilityPackRouteImport.update({
    id: '/services/accountability-pack',
    path: '/services/accountability-pack',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsBusinessIntelligenceRoute =
  SolutionsBusinessIntelligenceRouteImport.update({
    id: '/solutions/business-intelligence',
    path: '/solutions/business-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsDocumentVaultRoute = SolutionsDocumentVaultRouteImport.update({
  id: '/solutions/document-vault',
  path: '/solutions/document-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsExpenseEntriesRoute = SolutionsExpenseEntriesRouteImport.update({
  id: '/solutions/expense-entries',
  path: '/solutions/expense-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinancialControlRoute =
  SolutionsFinancialControlRouteImport.update({
    id: '/solutions/financial-control',
    path: '/solutions/financial-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsInnrlyPayRoute = SolutionsInnrlyPayRouteImport.update({
  id: '/solutions/innrly-pay',
  path: '/solutions/innrly-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsInnrlyShiftRoute = SolutionsInnrlyShiftRouteImport.update({
  id: '/solutions/innrly-shift',
  path: '/solutions/innrly-shift',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsLaborWorkforceRoute = SolutionsLaborWorkforceRouteImport.update({
  id: '/solutions/labor-workforce',
  path: '/solutions/labor-workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsOperationsAutomationRoute =
  SolutionsOperationsAutomationRouteImport.update({
    id: '/solutions/operations-automation',
    path: '/solutions/operations-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsReconciliationRoute = SolutionsReconciliationRouteImport.update({
  id: '/solutions/reconciliation',
  path: '/solutions/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/control-hub': typeof ControlHubRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/hotel-back-office-automation': typeof HotelBackOfficeAutomationRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/orb-preview': typeof OrbPreviewRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/boutique-group': typeof CaseStudiesBoutiqueGroupRoute
  '/case-studies/extended-stay-portfolio': typeof CaseStudiesExtendedStayPortfolioRoute
  '/case-studies/hilton-management-company': typeof CaseStudiesHiltonManagementCompanyRoute
  '/case-studies/midwest-portfolio': typeof CaseStudiesMidwestPortfolioRoute
  '/case-studies/urban-full-service': typeof CaseStudiesUrbanFullServiceRoute
  '/compare/innrly-vs-actabl': typeof CompareInnrlyVsActablRoute
  '/compare/innrly-vs-aptech': typeof CompareInnrlyVsAptechRoute
  '/compare/innrly-vs-hotel-effectiveness': typeof CompareInnrlyVsHotelEffectivenessRoute
  '/compare/innrly-vs-m3': typeof CompareInnrlyVsM3Route
  '/compare/innrly-vs-nimble': typeof CompareInnrlyVsNimbleRoute
  '/compare/innrly-vs-otelier': typeof CompareInnrlyVsOtelierRoute
  '/compare/innrly-vs-profitsage': typeof CompareInnrlyVsProfitsageRoute
  '/control-hub/blogs': typeof ControlHubBlogsRoute
  '/control-hub/logs': typeof ControlHubLogsRoute
  '/control-hub/newsletters': typeof ControlHubNewslettersRoute
  '/control-hub/onboarding': typeof ControlHubOnboardingRoute
  '/control-hub/seo': typeof ControlHubSeoRoute
  '/control-hub/settings': typeof ControlHubSettingsRoute
  '/control-hub/testimonials': typeof ControlHubTestimonialsRoute
  '/control-hub/trials': typeof ControlHubTrialsRoute
  '/control-hub/users': typeof ControlHubUsersRoute
  '/industries/extended-stay': typeof IndustriesExtendedStayRoute
  '/industries/full-service': typeof IndustriesFullServiceRoute
  '/industries/select-service': typeof IndustriesSelectServiceRoute
  '/integrations/cloudbeds': typeof IntegrationsCloudbedsRoute
  '/integrations/inn-flow': typeof IntegrationsInnFlowRoute
  '/integrations/m3': typeof IntegrationsM3Route
  '/integrations/mews': typeof IntegrationsMewsRoute
  '/integrations/opera': typeof IntegrationsOperaRoute
  '/integrations/quickbooks': typeof IntegrationsQuickbooksRoute
  '/integrations/sage-intacct': typeof IntegrationsSageIntacctRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/subscription': typeof LegalSubscriptionRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/accountability-pack': typeof ServicesAccountabilityPackRoute
  '/solutions/business-intelligence': typeof SolutionsBusinessIntelligenceRoute
  '/solutions/document-vault': typeof SolutionsDocumentVaultRoute
  '/solutions/expense-entries': typeof SolutionsExpenseEntriesRoute
  '/solutions/financial-control': typeof SolutionsFinancialControlRoute
  '/solutions/innrly-pay': typeof SolutionsInnrlyPayRoute
  '/solutions/innrly-shift': typeof SolutionsInnrlyShiftRoute
  '/solutions/labor-workforce': typeof SolutionsLaborWorkforceRoute
  '/solutions/operations-automation': typeof SolutionsOperationsAutomationRoute
  '/solutions/reconciliation': typeof SolutionsReconciliationRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/control-hub/': typeof ControlHubIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/hotel-back-office-automation': typeof HotelBackOfficeAutomationRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/orb-preview': typeof OrbPreviewRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/boutique-group': typeof CaseStudiesBoutiqueGroupRoute
  '/case-studies/extended-stay-portfolio': typeof CaseStudiesExtendedStayPortfolioRoute
  '/case-studies/hilton-management-company': typeof CaseStudiesHiltonManagementCompanyRoute
  '/case-studies/midwest-portfolio': typeof CaseStudiesMidwestPortfolioRoute
  '/case-studies/urban-full-service': typeof CaseStudiesUrbanFullServiceRoute
  '/compare/innrly-vs-actabl': typeof CompareInnrlyVsActablRoute
  '/compare/innrly-vs-aptech': typeof CompareInnrlyVsAptechRoute
  '/compare/innrly-vs-hotel-effectiveness': typeof CompareInnrlyVsHotelEffectivenessRoute
  '/compare/innrly-vs-m3': typeof CompareInnrlyVsM3Route
  '/compare/innrly-vs-nimble': typeof CompareInnrlyVsNimbleRoute
  '/compare/innrly-vs-otelier': typeof CompareInnrlyVsOtelierRoute
  '/compare/innrly-vs-profitsage': typeof CompareInnrlyVsProfitsageRoute
  '/control-hub/blogs': typeof ControlHubBlogsRoute
  '/control-hub/logs': typeof ControlHubLogsRoute
  '/control-hub/newsletters': typeof ControlHubNewslettersRoute
  '/control-hub/onboarding': typeof ControlHubOnboardingRoute
  '/control-hub/seo': typeof ControlHubSeoRoute
  '/control-hub/settings': typeof ControlHubSettingsRoute
  '/control-hub/testimonials': typeof ControlHubTestimonialsRoute
  '/control-hub/trials': typeof ControlHubTrialsRoute
  '/control-hub/users': typeof ControlHubUsersRoute
  '/industries/extended-stay': typeof IndustriesExtendedStayRoute
  '/industries/full-service': typeof IndustriesFullServiceRoute
  '/industries/select-service': typeof IndustriesSelectServiceRoute
  '/integrations/cloudbeds': typeof IntegrationsCloudbedsRoute
  '/integrations/inn-flow': typeof IntegrationsInnFlowRoute
  '/integrations/m3': typeof IntegrationsM3Route
  '/integrations/mews': typeof IntegrationsMewsRoute
  '/integrations/opera': typeof IntegrationsOperaRoute
  '/integrations/quickbooks': typeof IntegrationsQuickbooksRoute
  '/integrations/sage-intacct': typeof IntegrationsSageIntacctRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/subscription': typeof LegalSubscriptionRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/accountability-pack': typeof ServicesAccountabilityPackRoute
  '/solutions/business-intelligence': typeof SolutionsBusinessIntelligenceRoute
  '/solutions/document-vault': typeof SolutionsDocumentVaultRoute
  '/solutions/expense-entries': typeof SolutionsExpenseEntriesRoute
  '/solutions/financial-control': typeof SolutionsFinancialControlRoute
  '/solutions/innrly-pay': typeof SolutionsInnrlyPayRoute
  '/solutions/innrly-shift': typeof SolutionsInnrlyShiftRoute
  '/solutions/labor-workforce': typeof SolutionsLaborWorkforceRoute
  '/solutions/operations-automation': typeof SolutionsOperationsAutomationRoute
  '/solutions/reconciliation': typeof SolutionsReconciliationRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/compare': typeof CompareIndexRoute
  '/control-hub': typeof ControlHubIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/control-hub': typeof ControlHubRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/hotel-back-office-automation': typeof HotelBackOfficeAutomationRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/orb-preview': typeof OrbPreviewRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/boutique-group': typeof CaseStudiesBoutiqueGroupRoute
  '/case-studies/extended-stay-portfolio': typeof CaseStudiesExtendedStayPortfolioRoute
  '/case-studies/hilton-management-company': typeof CaseStudiesHiltonManagementCompanyRoute
  '/case-studies/midwest-portfolio': typeof CaseStudiesMidwestPortfolioRoute
  '/case-studies/urban-full-service': typeof CaseStudiesUrbanFullServiceRoute
  '/compare/innrly-vs-actabl': typeof CompareInnrlyVsActablRoute
  '/compare/innrly-vs-aptech': typeof CompareInnrlyVsAptechRoute
  '/compare/innrly-vs-hotel-effectiveness': typeof CompareInnrlyVsHotelEffectivenessRoute
  '/compare/innrly-vs-m3': typeof CompareInnrlyVsM3Route
  '/compare/innrly-vs-nimble': typeof CompareInnrlyVsNimbleRoute
  '/compare/innrly-vs-otelier': typeof CompareInnrlyVsOtelierRoute
  '/compare/innrly-vs-profitsage': typeof CompareInnrlyVsProfitsageRoute
  '/control-hub/blogs': typeof ControlHubBlogsRoute
  '/control-hub/logs': typeof ControlHubLogsRoute
  '/control-hub/newsletters': typeof ControlHubNewslettersRoute
  '/control-hub/onboarding': typeof ControlHubOnboardingRoute
  '/control-hub/seo': typeof ControlHubSeoRoute
  '/control-hub/settings': typeof ControlHubSettingsRoute
  '/control-hub/testimonials': typeof ControlHubTestimonialsRoute
  '/control-hub/trials': typeof ControlHubTrialsRoute
  '/control-hub/users': typeof ControlHubUsersRoute
  '/industries/extended-stay': typeof IndustriesExtendedStayRoute
  '/industries/full-service': typeof IndustriesFullServiceRoute
  '/industries/select-service': typeof IndustriesSelectServiceRoute
  '/integrations/cloudbeds': typeof IntegrationsCloudbedsRoute
  '/integrations/inn-flow': typeof IntegrationsInnFlowRoute
  '/integrations/m3': typeof IntegrationsM3Route
  '/integrations/mews': typeof IntegrationsMewsRoute
  '/integrations/opera': typeof IntegrationsOperaRoute
  '/integrations/quickbooks': typeof IntegrationsQuickbooksRoute
  '/integrations/sage-intacct': typeof IntegrationsSageIntacctRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/subscription': typeof LegalSubscriptionRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/accountability-pack': typeof ServicesAccountabilityPackRoute
  '/solutions/business-intelligence': typeof SolutionsBusinessIntelligenceRoute
  '/solutions/document-vault': typeof SolutionsDocumentVaultRoute
  '/solutions/expense-entries': typeof SolutionsExpenseEntriesRoute
  '/solutions/financial-control': typeof SolutionsFinancialControlRoute
  '/solutions/innrly-pay': typeof SolutionsInnrlyPayRoute
  '/solutions/innrly-shift': typeof SolutionsInnrlyShiftRoute
  '/solutions/labor-workforce': typeof SolutionsLaborWorkforceRoute
  '/solutions/operations-automation': typeof SolutionsOperationsAutomationRoute
  '/solutions/reconciliation': typeof SolutionsReconciliationRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/control-hub/': typeof ControlHubIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/control-hub'
    | '/developers'
    | '/features'
    | '/glossary'
    | '/hotel-back-office-automation'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/onboarding'
    | '/orb-preview'
    | '/pricing'
    | '/robots.txt'
    | '/roi-calculator'
    | '/security'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/case-studies/boutique-group'
    | '/case-studies/extended-stay-portfolio'
    | '/case-studies/hilton-management-company'
    | '/case-studies/midwest-portfolio'
    | '/case-studies/urban-full-service'
    | '/compare/innrly-vs-actabl'
    | '/compare/innrly-vs-aptech'
    | '/compare/innrly-vs-hotel-effectiveness'
    | '/compare/innrly-vs-m3'
    | '/compare/innrly-vs-nimble'
    | '/compare/innrly-vs-otelier'
    | '/compare/innrly-vs-profitsage'
    | '/control-hub/blogs'
    | '/control-hub/logs'
    | '/control-hub/newsletters'
    | '/control-hub/onboarding'
    | '/control-hub/seo'
    | '/control-hub/settings'
    | '/control-hub/testimonials'
    | '/control-hub/trials'
    | '/control-hub/users'
    | '/industries/extended-stay'
    | '/industries/full-service'
    | '/industries/select-service'
    | '/integrations/cloudbeds'
    | '/integrations/inn-flow'
    | '/integrations/m3'
    | '/integrations/mews'
    | '/integrations/opera'
    | '/integrations/quickbooks'
    | '/integrations/sage-intacct'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/subscription'
    | '/legal/terms'
    | '/services/accountability-pack'
    | '/solutions/business-intelligence'
    | '/solutions/document-vault'
    | '/solutions/expense-entries'
    | '/solutions/financial-control'
    | '/solutions/innrly-pay'
    | '/solutions/innrly-shift'
    | '/solutions/labor-workforce'
    | '/solutions/operations-automation'
    | '/solutions/reconciliation'
    | '/blog/'
    | '/case-studies/'
    | '/compare/'
    | '/control-hub/'
    | '/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/developers'
    | '/features'
    | '/glossary'
    | '/hotel-back-office-automation'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/onboarding'
    | '/orb-preview'
    | '/pricing'
    | '/robots.txt'
    | '/roi-calculator'
    | '/security'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/case-studies/boutique-group'
    | '/case-studies/extended-stay-portfolio'
    | '/case-studies/hilton-management-company'
    | '/case-studies/midwest-portfolio'
    | '/case-studies/urban-full-service'
    | '/compare/innrly-vs-actabl'
    | '/compare/innrly-vs-aptech'
    | '/compare/innrly-vs-hotel-effectiveness'
    | '/compare/innrly-vs-m3'
    | '/compare/innrly-vs-nimble'
    | '/compare/innrly-vs-otelier'
    | '/compare/innrly-vs-profitsage'
    | '/control-hub/blogs'
    | '/control-hub/logs'
    | '/control-hub/newsletters'
    | '/control-hub/onboarding'
    | '/control-hub/seo'
    | '/control-hub/settings'
    | '/control-hub/testimonials'
    | '/control-hub/trials'
    | '/control-hub/users'
    | '/industries/extended-stay'
    | '/industries/full-service'
    | '/industries/select-service'
    | '/integrations/cloudbeds'
    | '/integrations/inn-flow'
    | '/integrations/m3'
    | '/integrations/mews'
    | '/integrations/opera'
    | '/integrations/quickbooks'
    | '/integrations/sage-intacct'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/subscription'
    | '/legal/terms'
    | '/services/accountability-pack'
    | '/solutions/business-intelligence'
    | '/solutions/document-vault'
    | '/solutions/expense-entries'
    | '/solutions/financial-control'
    | '/solutions/innrly-pay'
    | '/solutions/innrly-shift'
    | '/solutions/labor-workforce'
    | '/solutions/operations-automation'
    | '/solutions/reconciliation'
    | '/blog'
    | '/case-studies'
    | '/compare'
    | '/control-hub'
    | '/integrations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/control-hub'
    | '/developers'
    | '/features'
    | '/glossary'
    | '/hotel-back-office-automation'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/onboarding'
    | '/orb-preview'
    | '/pricing'
    | '/robots.txt'
    | '/roi-calculator'
    | '/security'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/case-studies/boutique-group'
    | '/case-studies/extended-stay-portfolio'
    | '/case-studies/hilton-management-company'
    | '/case-studies/midwest-portfolio'
    | '/case-studies/urban-full-service'
    | '/compare/innrly-vs-actabl'
    | '/compare/innrly-vs-aptech'
    | '/compare/innrly-vs-hotel-effectiveness'
    | '/compare/innrly-vs-m3'
    | '/compare/innrly-vs-nimble'
    | '/compare/innrly-vs-otelier'
    | '/compare/innrly-vs-profitsage'
    | '/control-hub/blogs'
    | '/control-hub/logs'
    | '/control-hub/newsletters'
    | '/control-hub/onboarding'
    | '/control-hub/seo'
    | '/control-hub/settings'
    | '/control-hub/testimonials'
    | '/control-hub/trials'
    | '/control-hub/users'
    | '/industries/extended-stay'
    | '/industries/full-service'
    | '/industries/select-service'
    | '/integrations/cloudbeds'
    | '/integrations/inn-flow'
    | '/integrations/m3'
    | '/integrations/mews'
    | '/integrations/opera'
    | '/integrations/quickbooks'
    | '/integrations/sage-intacct'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/subscription'
    | '/legal/terms'
    | '/services/accountability-pack'
    | '/solutions/business-intelligence'
    | '/solutions/document-vault'
    | '/solutions/expense-entries'
    | '/solutions/financial-control'
    | '/solutions/innrly-pay'
    | '/solutions/innrly-shift'
    | '/solutions/labor-workforce'
    | '/solutions/operations-automation'
    | '/solutions/reconciliation'
    | '/blog/'
    | '/case-studies/'
    | '/compare/'
    | '/control-hub/'
    | '/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ControlHubRoute: typeof ControlHubRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  FeaturesRoute: typeof FeaturesRoute
  GlossaryRoute: typeof GlossaryRoute
  HotelBackOfficeAutomationRoute: typeof HotelBackOfficeAutomationRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OnboardingRoute: typeof OnboardingRoute
  OrbPreviewRoute: typeof OrbPreviewRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CaseStudiesBoutiqueGroupRoute: typeof CaseStudiesBoutiqueGroupRoute
  CaseStudiesExtendedStayPortfolioRoute: typeof CaseStudiesExtendedStayPortfolioRoute
  CaseStudiesHiltonManagementCompanyRoute: typeof CaseStudiesHiltonManagementCompanyRoute
  CaseStudiesMidwestPortfolioRoute: typeof CaseStudiesMidwestPortfolioRoute
  CaseStudiesUrbanFullServiceRoute: typeof CaseStudiesUrbanFullServiceRoute
  CompareInnrlyVsActablRoute: typeof CompareInnrlyVsActablRoute
  CompareInnrlyVsAptechRoute: typeof CompareInnrlyVsAptechRoute
  CompareInnrlyVsHotelEffectivenessRoute: typeof CompareInnrlyVsHotelEffectivenessRoute
  CompareInnrlyVsM3Route: typeof CompareInnrlyVsM3Route
  CompareInnrlyVsNimbleRoute: typeof CompareInnrlyVsNimbleRoute
  CompareInnrlyVsOtelierRoute: typeof CompareInnrlyVsOtelierRoute
  CompareInnrlyVsProfitsageRoute: typeof CompareInnrlyVsProfitsageRoute
  IndustriesExtendedStayRoute: typeof IndustriesExtendedStayRoute
  IndustriesFullServiceRoute: typeof IndustriesFullServiceRoute
  IndustriesSelectServiceRoute: typeof IndustriesSelectServiceRoute
  IntegrationsCloudbedsRoute: typeof IntegrationsCloudbedsRoute
  IntegrationsInnFlowRoute: typeof IntegrationsInnFlowRoute
  IntegrationsM3Route: typeof IntegrationsM3Route
  IntegrationsMewsRoute: typeof IntegrationsMewsRoute
  IntegrationsOperaRoute: typeof IntegrationsOperaRoute
  IntegrationsQuickbooksRoute: typeof IntegrationsQuickbooksRoute
  IntegrationsSageIntacctRoute: typeof IntegrationsSageIntacctRoute
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  LegalSubscriptionRoute: typeof LegalSubscriptionRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ServicesAccountabilityPackRoute: typeof ServicesAccountabilityPackRoute
  SolutionsBusinessIntelligenceRoute: typeof SolutionsBusinessIntelligenceRoute
  SolutionsDocumentVaultRoute: typeof SolutionsDocumentVaultRoute
  SolutionsExpenseEntriesRoute: typeof SolutionsExpenseEntriesRoute
  SolutionsFinancialControlRoute: typeof SolutionsFinancialControlRoute
  SolutionsInnrlyPayRoute: typeof SolutionsInnrlyPayRoute
  SolutionsInnrlyShiftRoute: typeof SolutionsInnrlyShiftRoute
  SolutionsLaborWorkforceRoute: typeof SolutionsLaborWorkforceRoute
  SolutionsOperationsAutomationRoute: typeof SolutionsOperationsAutomationRoute
  SolutionsReconciliationRoute: typeof SolutionsReconciliationRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-hub': {
      id: '/control-hub'
      path: '/control-hub'
      fullPath: '/control-hub'
      preLoaderRoute: typeof ControlHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-back-office-automation': {
      id: '/hotel-back-office-automation'
      path: '/hotel-back-office-automation'
      fullPath: '/hotel-back-office-automation'
      preLoaderRoute: typeof HotelBackOfficeAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orb-preview': {
      id: '/orb-preview'
      path: '/orb-preview'
      fullPath: '/orb-preview'
      preLoaderRoute: typeof OrbPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/boutique-group': {
      id: '/case-studies/boutique-group'
      path: '/case-studies/boutique-group'
      fullPath: '/case-studies/boutique-group'
      preLoaderRoute: typeof CaseStudiesBoutiqueGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/extended-stay-portfolio': {
      id: '/case-studies/extended-stay-portfolio'
      path: '/case-studies/extended-stay-portfolio'
      fullPath: '/case-studies/extended-stay-portfolio'
      preLoaderRoute: typeof CaseStudiesExtendedStayPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/hilton-management-company': {
      id: '/case-studies/hilton-management-company'
      path: '/case-studies/hilton-management-company'
      fullPath: '/case-studies/hilton-management-company'
      preLoaderRoute: typeof CaseStudiesHiltonManagementCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/midwest-portfolio': {
      id: '/case-studies/midwest-portfolio'
      path: '/case-studies/midwest-portfolio'
      fullPath: '/case-studies/midwest-portfolio'
      preLoaderRoute: typeof CaseStudiesMidwestPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/urban-full-service': {
      id: '/case-studies/urban-full-service'
      path: '/case-studies/urban-full-service'
      fullPath: '/case-studies/urban-full-service'
      preLoaderRoute: typeof CaseStudiesUrbanFullServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/innrly-vs-actabl': {
      id: '/compare/innrly-vs-actabl'
      path: '/compare/innrly-vs-actabl'
      fullPath: '/compare/innrly-vs-actabl'
      preLoaderRoute: typeof CompareInnrlyVsActablRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/innrly-vs-aptech': {
      id: '/compare/innrly-vs-aptech'
      path: '/compare/innrly-vs-aptech'
      fullPath: '/compare/innrly-vs-aptech'
      preLoaderRoute: typeof CompareInnrlyVsAptechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/innrly-vs-hotel-effectiveness': {
      id: '/compare/innrly-vs-hotel-effectiveness'
      path: '/compare/innrly-vs-hotel-effectiveness'
      fullPath: '/compare/innrly-vs-hotel-effectiveness'
      preLoaderRoute: typeof CompareInnrlyVsHotelEffectivenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/innrly-vs-m3': {
      id: '/compare/innrly-vs-m3'
      path: '/compare/innrly-vs-m3'
      fullPath: '/compare/innrly-vs-m3'
      preLoaderRoute: typeof CompareInnrlyVsM3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/innrly-vs-nimble': {
      id: '/compare/innrly-vs-nimble'
      path: '/compare/innrly-vs-nimble'
      fullPath: '/compare/innrly-vs-nimble'
      preLoaderRoute: typeof CompareInnrlyVsNimbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/innrly-vs-otelier': {
      id: '/compare/innrly-vs-otelier'
      path: '/compare/innrly-vs-otelier'
      fullPath: '/compare/innrly-vs-otelier'
      preLoaderRoute: typeof CompareInnrlyVsOtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/innrly-vs-profitsage': {
      id: '/compare/innrly-vs-profitsage'
      path: '/compare/innrly-vs-profitsage'
      fullPath: '/compare/innrly-vs-profitsage'
      preLoaderRoute: typeof CompareInnrlyVsProfitsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-hub/': {
      id: '/control-hub/'
      path: '/'
      fullPath: '/control-hub/'
      preLoaderRoute: typeof ControlHubIndexRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/blogs': {
      id: '/control-hub/blogs'
      path: '/blogs'
      fullPath: '/control-hub/blogs'
      preLoaderRoute: typeof ControlHubBlogsRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/logs': {
      id: '/control-hub/logs'
      path: '/logs'
      fullPath: '/control-hub/logs'
      preLoaderRoute: typeof ControlHubLogsRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/newsletters': {
      id: '/control-hub/newsletters'
      path: '/newsletters'
      fullPath: '/control-hub/newsletters'
      preLoaderRoute: typeof ControlHubNewslettersRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/onboarding': {
      id: '/control-hub/onboarding'
      path: '/onboarding'
      fullPath: '/control-hub/onboarding'
      preLoaderRoute: typeof ControlHubOnboardingRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/seo': {
      id: '/control-hub/seo'
      path: '/seo'
      fullPath: '/control-hub/seo'
      preLoaderRoute: typeof ControlHubSeoRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/settings': {
      id: '/control-hub/settings'
      path: '/settings'
      fullPath: '/control-hub/settings'
      preLoaderRoute: typeof ControlHubSettingsRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/testimonials': {
      id: '/control-hub/testimonials'
      path: '/testimonials'
      fullPath: '/control-hub/testimonials'
      preLoaderRoute: typeof ControlHubTestimonialsRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/trials': {
      id: '/control-hub/trials'
      path: '/trials'
      fullPath: '/control-hub/trials'
      preLoaderRoute: typeof ControlHubTrialsRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/control-hub/users': {
      id: '/control-hub/users'
      path: '/users'
      fullPath: '/control-hub/users'
      preLoaderRoute: typeof ControlHubUsersRouteImport
      parentRoute: typeof ControlHubRoute
    }
    '/industries/extended-stay': {
      id: '/industries/extended-stay'
      path: '/industries/extended-stay'
      fullPath: '/industries/extended-stay'
      preLoaderRoute: typeof IndustriesExtendedStayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/full-service': {
      id: '/industries/full-service'
      path: '/industries/full-service'
      fullPath: '/industries/full-service'
      preLoaderRoute: typeof IndustriesFullServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/select-service': {
      id: '/industries/select-service'
      path: '/industries/select-service'
      fullPath: '/industries/select-service'
      preLoaderRoute: typeof IndustriesSelectServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/cloudbeds': {
      id: '/integrations/cloudbeds'
      path: '/integrations/cloudbeds'
      fullPath: '/integrations/cloudbeds'
      preLoaderRoute: typeof IntegrationsCloudbedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/inn-flow': {
      id: '/integrations/inn-flow'
      path: '/integrations/inn-flow'
      fullPath: '/integrations/inn-flow'
      preLoaderRoute: typeof IntegrationsInnFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/m3': {
      id: '/integrations/m3'
      path: '/integrations/m3'
      fullPath: '/integrations/m3'
      preLoaderRoute: typeof IntegrationsM3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/mews': {
      id: '/integrations/mews'
      path: '/integrations/mews'
      fullPath: '/integrations/mews'
      preLoaderRoute: typeof IntegrationsMewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/opera': {
      id: '/integrations/opera'
      path: '/integrations/opera'
      fullPath: '/integrations/opera'
      preLoaderRoute: typeof IntegrationsOperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/quickbooks': {
      id: '/integrations/quickbooks'
      path: '/integrations/quickbooks'
      fullPath: '/integrations/quickbooks'
      preLoaderRoute: typeof IntegrationsQuickbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/sage-intacct': {
      id: '/integrations/sage-intacct'
      path: '/integrations/sage-intacct'
      fullPath: '/integrations/sage-intacct'
      preLoaderRoute: typeof IntegrationsSageIntacctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/legal/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/legal/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/subscription': {
      id: '/legal/subscription'
      path: '/legal/subscription'
      fullPath: '/legal/subscription'
      preLoaderRoute: typeof LegalSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/accountability-pack': {
      id: '/services/accountability-pack'
      path: '/services/accountability-pack'
      fullPath: '/services/accountability-pack'
      preLoaderRoute: typeof ServicesAccountabilityPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/business-intelligence': {
      id: '/solutions/business-intelligence'
      path: '/solutions/business-intelligence'
      fullPath: '/solutions/business-intelligence'
      preLoaderRoute: typeof SolutionsBusinessIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/document-vault': {
      id: '/solutions/document-vault'
      path: '/solutions/document-vault'
      fullPath: '/solutions/document-vault'
      preLoaderRoute: typeof SolutionsDocumentVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/expense-entries': {
      id: '/solutions/expense-entries'
      path: '/solutions/expense-entries'
      fullPath: '/solutions/expense-entries'
      preLoaderRoute: typeof SolutionsExpenseEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/financial-control': {
      id: '/solutions/financial-control'
      path: '/solutions/financial-control'
      fullPath: '/solutions/financial-control'
      preLoaderRoute: typeof SolutionsFinancialControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/innrly-pay': {
      id: '/solutions/innrly-pay'
      path: '/solutions/innrly-pay'
      fullPath: '/solutions/innrly-pay'
      preLoaderRoute: typeof SolutionsInnrlyPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/innrly-shift': {
      id: '/solutions/innrly-shift'
      path: '/solutions/innrly-shift'
      fullPath: '/solutions/innrly-shift'
      preLoaderRoute: typeof SolutionsInnrlyShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/labor-workforce': {
      id: '/solutions/labor-workforce'
      path: '/solutions/labor-workforce'
      fullPath: '/solutions/labor-workforce'
      preLoaderRoute: typeof SolutionsLaborWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/operations-automation': {
      id: '/solutions/operations-automation'
      path: '/solutions/operations-automation'
      fullPath: '/solutions/operations-automation'
      preLoaderRoute: typeof SolutionsOperationsAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/reconciliation': {
      id: '/solutions/reconciliation'
      path: '/solutions/reconciliation'
      fullPath: '/solutions/reconciliation'
      preLoaderRoute: typeof SolutionsReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ControlHubRouteChildren {
  ControlHubBlogsRoute: typeof ControlHubBlogsRoute
  ControlHubLogsRoute: typeof ControlHubLogsRoute
  ControlHubNewslettersRoute: typeof ControlHubNewslettersRoute
  ControlHubOnboardingRoute: typeof ControlHubOnboardingRoute
  ControlHubSeoRoute: typeof ControlHubSeoRoute
  ControlHubSettingsRoute: typeof ControlHubSettingsRoute
  ControlHubTestimonialsRoute: typeof ControlHubTestimonialsRoute
  ControlHubTrialsRoute: typeof ControlHubTrialsRoute
  ControlHubUsersRoute: typeof ControlHubUsersRoute
  ControlHubIndexRoute: typeof ControlHubIndexRoute
}

const ControlHubRouteChildren: ControlHubRouteChildren = {
  ControlHubBlogsRoute: ControlHubBlogsRoute,
  ControlHubLogsRoute: ControlHubLogsRoute,
  ControlHubNewslettersRoute: ControlHubNewslettersRoute,
  ControlHubOnboardingRoute: ControlHubOnboardingRoute,
  ControlHubSeoRoute: ControlHubSeoRoute,
  ControlHubSettingsRoute: ControlHubSettingsRoute,
  ControlHubTestimonialsRoute: ControlHubTestimonialsRoute,
  ControlHubTrialsRoute: ControlHubTrialsRoute,
  ControlHubUsersRoute: ControlHubUsersRoute,
  ControlHubIndexRoute: ControlHubIndexRoute,
}

const ControlHubRouteWithChildren = ControlHubRoute._addFileChildren(
  ControlHubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ControlHubRoute: ControlHubRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  FeaturesRoute: FeaturesRoute,
  GlossaryRoute: GlossaryRoute,
  HotelBackOfficeAutomationRoute: HotelBackOfficeAutomationRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OnboardingRoute: OnboardingRoute,
  OrbPreviewRoute: OrbPreviewRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  CaseStudiesBoutiqueGroupRoute: CaseStudiesBoutiqueGroupRoute,
  CaseStudiesExtendedStayPortfolioRoute: CaseStudiesExtendedStayPortfolioRoute,
  CaseStudiesHiltonManagementCompanyRoute:
    CaseStudiesHiltonManagementCompanyRoute,
  CaseStudiesMidwestPortfolioRoute: CaseStudiesMidwestPortfolioRoute,
  CaseStudiesUrbanFullServiceRoute: CaseStudiesUrbanFullServiceRoute,
  CompareInnrlyVsActablRoute: CompareInnrlyVsActablRoute,
  CompareInnrlyVsAptechRoute: CompareInnrlyVsAptechRoute,
  CompareInnrlyVsHotelEffectivenessRoute:
    CompareInnrlyVsHotelEffectivenessRoute,
  CompareInnrlyVsM3Route: CompareInnrlyVsM3Route,
  CompareInnrlyVsNimbleRoute: CompareInnrlyVsNimbleRoute,
  CompareInnrlyVsOtelierRoute: CompareInnrlyVsOtelierRoute,
  CompareInnrlyVsProfitsageRoute: CompareInnrlyVsProfitsageRoute,
  IndustriesExtendedStayRoute: IndustriesExtendedStayRoute,
  IndustriesFullServiceRoute: IndustriesFullServiceRoute,
  IndustriesSelectServiceRoute: IndustriesSelectServiceRoute,
  IntegrationsCloudbedsRoute: IntegrationsCloudbedsRoute,
  IntegrationsInnFlowRoute: IntegrationsInnFlowRoute,
  IntegrationsM3Route: IntegrationsM3Route,
  IntegrationsMewsRoute: IntegrationsMewsRoute,
  IntegrationsOperaRoute: IntegrationsOperaRoute,
  IntegrationsQuickbooksRoute: IntegrationsQuickbooksRoute,
  IntegrationsSageIntacctRoute: IntegrationsSageIntacctRoute,
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  LegalSubscriptionRoute: LegalSubscriptionRoute,
  LegalTermsRoute: LegalTermsRoute,
  ServicesAccountabilityPackRoute: ServicesAccountabilityPackRoute,
  SolutionsBusinessIntelligenceRoute: SolutionsBusinessIntelligenceRoute,
  SolutionsDocumentVaultRoute: SolutionsDocumentVaultRoute,
  SolutionsExpenseEntriesRoute: SolutionsExpenseEntriesRoute,
  SolutionsFinancialControlRoute: SolutionsFinancialControlRoute,
  SolutionsInnrlyPayRoute: SolutionsInnrlyPayRoute,
  SolutionsInnrlyShiftRoute: SolutionsInnrlyShiftRoute,
  SolutionsLaborWorkforceRoute: SolutionsLaborWorkforceRoute,
  SolutionsOperationsAutomationRoute: SolutionsOperationsAutomationRoute,
  SolutionsReconciliationRoute: SolutionsReconciliationRoute,
  BlogIndexRoute: BlogIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
